#
# ██████╗░██╗░░░██╗  ███████╗███╗░░██╗░█████╗░░█████╗░░██████╗░
# ██╔══██╗╚██╗░██╔╝  ██╔════╝████╗░██║██╔══██╗██╔══██╗██╔════╝░
# ██████╦╝░╚████╔╝░  █████╗░░██╔██╗██║██║░░╚═╝██║░░██║██║░░██╗░
# ██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║╚████║██║░░██╗██║░░██║██║░░╚██╗
# ██████╦╝░░░██║░░░  ███████╗██║░╚███║╚█████╔╝╚█████╔╝╚██████╔╝
# ╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░╚════╝░░╚════╝░░╚═════╝░
#
# Предметы
items-to-keep:
  - DIAMOND_SWORD
  - IRON_HELMET
keep-chance:
  DIAMOND_SWORD: 1.0 #100%
  IRON_HELMET: 0.7 #70%
# Сообщения
play-sound: true
show-title: true
show-message: true
sound-name: "ENTITY_PLAYER_LEVELUP"
title: "&bВы умерли!"
subtitle: "&eНо сохранили некоторые предметы"
chat-message: "&aВы сохранили некоторые предметы после смерти!"
